#
# Makefile for iRex ER0100
#

obj-$(CONFIG_MACH_PXA_IREX_ER0100)		+= irex_er0100.o

obj-$(CONFIG_PXA_IREX_ER0100_PCMCIA)     += irex_er0100_pcmcia.o
obj-$(CONFIG_PXA_IREX_ER0100_BUTTON)     += irex_er0100_button.o
obj-$(CONFIG_PXA_IREX_ER0100_BATTERY)     += irex_er0100_battery.o
